int size_array(int *array);
int pesquisaBinaria (int *array, int elem, int size);
int compareInts (const void * a, const void * b);
char *name_newfile(int n);
int *str_array(char *str, int n) ;
int* concatena_arrays (int a[],int asize, int b[], int bsize);
int* copyArray (int a[], int size);
char *where(char *pasta,char *data);
void validate_files(char *file1, char*file2,char *file3, int iterativo, int param, char*data, int query);
int validate_language(char *lan);